# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 350cc3d00f84d2132265879c579f0b703e89f56886d65f588b44f25102e4093024d2c458507cc2a4b5f2e9c23b1e7edb2e9364a079d1ad2ee31bc1e91b96e632

test:
  secret_key_base: e8e479bdecb1d353a77522976a5aff0747ee93b2813741470effd7c33d052d5a9cd8131669fd7c8c13f7f5c00a206f1e375d011b92b9efe503af6a1ae56704d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
